### ISSUE TITLE
Database-wide options are missing in the database chart

### ISSUE THREAD

**Issue by vegichan** [nuodb/nuodb-helm-charts#108]
```
  ## database-wide options.
  # These are applied using the --database-options on the startup command
  # change these to values appropriate for this database
  # these options are applied to all processes in the database.
  options:
    ping-timeout: 60
    max-lost-archives: 0
```
